definitions:
  handlers.LoginRequest:
    properties:
      password:
        example: admin123
        type: string
      username:
        example: admin
        type: string
    required:
    - password
    - username
    type: object
  models.Product:
    properties:
      created_at:
        type: string
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      price:
        type: number
      stock:
        type: integer
      updated_at:
        type: string
    type: object
info:
  contact: {}
  description: Power Toys 后台管理系统 API 文档
  title: Power Toys API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: 用户登录并获取token
      parameters:
      - description: 登录信息
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: token和用户信息
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 错误信息
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: 认证失败
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 用户登录
      tags:
      - 认证
  /products:
    get:
      description: 获取所有商品
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 商品列表
          schema:
            items:
              $ref: '#/definitions/models.Product'
            type: array
        "401":
          description: 未授权
          schema:
            additionalProperties:
              type: string
            type: object
        "403":
          description: 权限不足
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: 获取商品列表
      tags:
      - 商品管理
    post:
      consumes:
      - application/json
      description: 创建新商品
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 商品信息
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.Product'
      produces:
      - application/json
      responses:
        "201":
          description: 创建成功的商品信息
          schema:
            $ref: '#/definitions/models.Product'
        "400":
          description: 请求参数错误
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: 未授权
          schema:
            additionalProperties:
              type: string
            type: object
        "403":
          description: 权限不足
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: 创建商品
      tags:
      - 商品管理
  /products/{id}:
    get:
      description: 根据ID获取商品详情
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 商品ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 商品详情
          schema:
            $ref: '#/definitions/models.Product'
        "400":
          description: ID格式错误
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: 未授权
          schema:
            additionalProperties:
              type: string
            type: object
        "403":
          description: 权限不足
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: 商品不存在
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: 获取商品详情
      tags:
      - 商品管理
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
